server:
  port: 9700
spring:
  application:
    name: mongo_boot
  data:
    mongodb:
      authentication-database: admin
      database: shop
      host: 47.92.157.135
      username: alex
      password: becauseofyou7
      port: 27017
      connections-per-host: 20
      min-connections-per-host: 20
logging:
  level:
    org .springframework.data.mongodb.core: debug